version: "3"
services:
  platzi_store_products:
    build:
      context: ./hacktzi_store_products
    ports:
      - "80"
    networks:
      - default
      - myserver_default
    environment:
      - VIRTUAL_HOST=api.hacktzi.tk
      - PORT=80
      - DB_HOST=db
      - DB_NAME=hacktzi-store-products-db
      - DB_USER=hacktzi-store-products-user-db
      - DB_PASSWORD=hacktzi-store-products-user-pw
      - DB_PORT=5432
    restart: always
    depends_on:
      - "db"
  db:
    image: postgres:13
    restart: always
    ports: 
      - "5432"
    environment:
      - POSTGRES_DB=hacktzi-store-products-db
      - POSTGRES_USER=hacktzi-store-products-user-db
      - POSTGRES_PASSWORD=hacktzi-store-products-user-pw
    volumes:
      - ./hacktzi_store_products-postgres:/var/lib/postgresql